### ISSUE TITLE
Unhandled Exception when calling getAvatar

### ISSUE THREAD

**Issue by spinapplications** [lukasgit/flutter_contacts#155]
@lukasgit 

I have the exact same issue with getAvatar as [reported here](https://github.com/lukasgit/flutter_contacts/issues/62#issue-523782962).

`Unhandled Exception: MissingPluginException(No implementation found for method getAvatar on channel github.com/clovisnicolas/flutter_contacts)`

I am using the dependency:
`contacts_service: ^0.4.6`

How can I change the reference to the  https://github.com/lukasgit/flutter_contacts branch as you suggested in your reply to the issue referred to above?

Thanks,
Solveig.

**Comment by jaypatel04** [comment]
For iOS, you don't need to call Avatar method separately as it is not implemented in iOS. Because in iOS, every details are populated as single unit where in Android, the details are populated from distributed tables (separate tables), so there is a performance penalty in Android. So, in Android you need to call getAvatar as and when required.

**Comment by spinapplications** [comment]
@jaypatel04 That makes sense, thank you
