### ISSUE TITLE
The display name and the given name for iOS 14 doesnt work

### ISSUE THREAD

**Issue by pauloj2000** [lukasgit/flutter_contacts#166]
I'm trying to use these properties on iOS, but comes a empty text. Android works perfectly.

**Comment by mzafer** [comment]
Hi @pauloj2000 , were you able to find a fix for this issue ? I am running into the same

**Comment by buraktabn** [comment]
This issue still continues for me. Cannot call`displayName` from the Contact Model. It's null.

**Comment by lukasgit** [comment]
@pauloj2000 @mzafer @buraktabn please feel free to contribute a working PR to stable branch. Thanks

**Comment by buraktabn** [comment]
I had some time to do a little digging about the problem. I run the example app and had a bunch of exceptions. 

In **contacts_list_page.dart** we request avatar of the user from method channel.
https://github.com/lukasgit/flutter_contacts/blob/4838a37a8036ea74f46fef4ccc48e5b5217b6dbc/example/lib/contacts_list_page.dart#L35-L38

https://github.com/lukasgit/flutter_contacts/blob/4838a37a8036ea74f46fef4ccc48e5b5217b6dbc/lib/contacts_service.dart#L81-L86

However, there's nowhere to call from [SwiftContactsServicePlugin.swift](https://github.com/lukasgit/flutter_contacts/blob/master/ios/Classes/SwiftContactsServicePlugin.swift#L26). I created a new case called `getAvatar` and returned `nil` to find out if this was the problem. It was not and had nothing to with the display name. 

The issue for me was that I didn't know you could save just a number without any additional fields. Therefore, I could not get the display name. Since there are no initials to show it threw an error. With some basic null checks, I solved my problem.
