### ISSUE TITLE
not found ContactsServicePlugin.h

### ISSUE THREAD

**Issue by JoseVargas05** [lukasgit/flutter_contacts#38]
hello, i can't fix this problem:

![imagen](https://user-images.githubusercontent.com/33564334/66243398-157ff380-e6ca-11e9-88c1-440b232c9a1a.png)

in Android work very good but i want do to ios, i hope you can help me.

**Comment by lukasgit** [comment]
@JoseVargas05 swamped on my end... anyone willing and able to help follow up on this?

**Comment by Carc13** [comment]
The problem is that you have created your project with "flutter create myApp", and depending on the version of flutter may have the option "switf support" disabled, if you create the project with android studio, check that option, and flutter updated, you can solve that problem, but there will come another problem, which I have.

**Comment by vini2001** [comment]
If you still needs it, just remove contacts_service/ from #import "contacts_service/...

**Comment by lukasgit** [comment]
1. Delete the ios folder (you might want to create a backup first)
2. Run this command in the root of the project:  `flutter create -i swift .`

**Comment by vini2001** [comment]
> 1. Delete the ios folder (you might want to create a backup first)
> 2. Run this command in the root of the project:  `flutter create -i swift .`

Even doing that might be necessary to remove contacts_service/ from #import "contacts_service/.... At least it was the only way I could manage to work it

**Comment by JoseVargas05** [comment]
hello i found one possible solution, works for me... in terminal go ios folder in project and ejecute: pod clean - pod install - pod init
